<?php
/**
 * CountryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fax.to REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CountryApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CountryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for areacodesCountryCodeStateIdGet
     *
     * .
     *
     */
    public function testAreacodesCountryCodeStateIdGet()
    {
    }

    /**
     * Test case for countriesCountryCodeDidgroupsGet
     *
     * .
     *
     */
    public function testCountriesCountryCodeDidgroupsGet()
    {
    }

    /**
     * Test case for countriesDidgroupsDidGroupIdProvisionPost
     *
     * .
     *
     */
    public function testCountriesDidgroupsDidGroupIdProvisionPost()
    {
    }

    /**
     * Test case for countriesGet
     *
     * .
     *
     */
    public function testCountriesGet()
    {
    }

    /**
     * Test case for statesCountryCodeGet
     *
     * .
     *
     */
    public function testStatesCountryCodeGet()
    {
    }
}
